// <auto-generated />
namespace Xcendant.HASL.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_profile_image : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_profile_image));
        
        string IMigrationMetadata.Id
        {
            get { return "201512131334244_added_profile_image"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
